
# ˝æ›ø‚≈‰÷√spring:
spring:
  datasource:
    url: jdbc:mysql://192.168.128.1:3306/test?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver